# Generated by Django 4.0.3 on 2022-10-03 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='label')),
                ('price', models.DecimalField(
                    decimal_places=2, max_digits=4, verbose_name='price')),
                ('qrcode_id', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(
                    '[A-Z0-9]{8}', message='The QR code identifier must contain exactly 8 characters in the A-Z,0-9 range')], verbose_name='QR code identifier')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'unique_together': {('qrcode_id', 'event')},
            },
        ),
    ]
