# Generated by Django 3.2.5 on 2021-07-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('buy_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sell_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(through='sep_inventory.SaleItem', to='sep_inventory.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.paymentmethod'),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('products', models.ManyToManyField(to='sep_inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.product')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
