# Generated by Django 3.2.5 on 2021-07-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sep_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
