# Generated by Django 3.2.6 on 2021-08-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep_inventory', '0003_auto_20210829_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(through='sep_inventory.SaleItem', to='sep_inventory.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.sale'),
        ),
    ]
