# Generated by Django 3.2.6 on 2021-08-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep_inventory', '0004_auto_20210829_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_to_sale', to='sep_inventory.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_to_product', to='sep_inventory.sale'),
        ),
    ]
