# Generated by Django 4.0.3 on 2022-07-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep_inventory', '0007_auto_20210914_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name': 'pack', 'verbose_name_plural': 'packs'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'sale item', 'verbose_name_plural': 'sale items'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletion date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.SmallIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='products',
            field=models.ManyToManyField(to='sep_inventory.product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=24, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='selling price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletion date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sep_inventory.paymentmethod', verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_to_sale', to='sep_inventory.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.SmallIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_to_product', to='sep_inventory.sale', verbose_name='sale'),
        ),
    ]
