# Generated by Django 4.0.3 on 2022-10-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep_inventory', '0009_packitem_alter_pack_products_packitem_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sep_inventory.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sep_inventory.pack', verbose_name='pack'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_to_product', to='sep_inventory.sale', verbose_name='sale'),
        ),
    ]
